In [1]:
import tensorflow as tf
from keras.layers import  Input,SimpleRNN, Dense, Flatten
from keras.optimizers import SGD , Adam
from keras.models  import Model

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [2]:
# Things you should automatically know and have memorized
# N = number of samples
# T = sequences length
# D = number of input features
# M = number of hidden units
# K = number of output units

N = 1
T = 10
D = 3
K = 2
X = np.random.randn(N, T, D)

In [3]:
# Make an RNN

M = 5
i = Input(shape=(T, D))
x = SimpleRNN(M)(i)
x = Dense(K)(x)

model = Model(i,x)
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 10, 3)]           0         
                                                                 
 simple_rnn (SimpleRNN)      (None, 5)                 45        
                                                                 
 dense (Dense)               (None, 2)                 12        
                                                                 
Total params: 57 (228.00 Byte)
Trainable params: 57 (228.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [5]:
Yhat = model.predict(X)
print(Yhat)

1/1 [==============================] - 0s 20ms/step
[[-0.8004683  0.1972957]]


In [6]:
model.layers[1].get_weights()

[array([[ 0.8587045 ,  0.11887538, -0.32026845, -0.8606698 , -0.37500188],
        [ 0.24342817, -0.09397078,  0.10784602, -0.32140678,  0.18542975],
        [-0.628387  ,  0.41513413,  0.35227543, -0.5977104 ,  0.22070152]],
       dtype=float32),
 array([[-0.6842694 , -0.4210686 ,  0.41336527, -0.23172005,  0.36043242],
        [-0.18252863, -0.35283405,  0.08975774,  0.85939366, -0.30915648],
        [-0.6315628 ,  0.64874256, -0.02520312, -0.01749356, -0.42346218],
        [ 0.30148175,  0.02703518,  0.82222444, -0.17263459, -0.45002463],
        [ 0.0932512 ,  0.5259388 ,  0.37997967,  0.42147332,  0.6266325 ]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32)]

In [7]:
a, b, c = model.layers[1].get_weights()
print(a.shape,b.shape,c.shape)

(3, 5) (5, 5) (5,)


In [8]:
Wx, Wh, bh = model.layers[1].get_weights()
wo, bo = model.layers[2].get_weights()

In [ ]:
h_last = np.zeros(M)
x = X[0]
Yhats = []

for t in range(T):
  h = np.tanh(x[t].dot(Wx) + h_last.dot[Wh] + bh)
  y = h.sot(wo) + bo
  Yhats.append(y)